name: Run thunder_admin visual regression tests

on:
  pull_request:
    paths-ignore:
      - '**.md'

  schedule:
    - cron:  '0 6 * * *'

jobs:
  ### Build job
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
#        SHARPEYE_BROWSER: ['chrome'] #, 'firefox']
        THUNDER: ['8.x-4.x']
#        DRUPAL_CORE: ['8.8.x']

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@master
      with:
        coverage: none
        php-version: '7.3'

    # Create-project with absolute path is broken in 1.10-RC;
    # setup-php action does not support passing composer version.
    - name: Downgrade composer
      run: sudo rm /usr/local/bin/composer; composer self-update 1.9.3

    - name: Install sqlite3 packages
      run: sudo apt-get install sqlite3

    - name: Get build environment
      run: git clone --depth 1 https://github.com/thunder/thunder-admin-tests.git -b task/github-actions ${HOME}/build/thunder/thunder-admin-tests

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-cache-

    - name: Cache NPM dependencies
      id: npm-cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-cache
        restore-keys: ${{ runner.os }}-npm-cache

    - name: Setup environment variables
      run: |
        echo "::add-path::$HOME/.composer/vendor/bin"
        echo "::add-path::$HOME/build/thunder/thunder-admin-tests/scripts"
        echo "::add-path::$HOME/build/test-dir/bin"

    - name: Build composer project
      run: build-codebase.sh
      env:
        THUNDER: ${{ matrix.THUNDER }}

    - name: Install application
      run: install-application.sh

    - name: Zip build
      run: cd ${HOME}; tar cfz build.tgz build/test-dir; mv build.tgz ${GITHUB_WORKSPACE}

    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build.tgz

  ### Visual regression testing job
  visual:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        SHARPEYE_BROWSER: ['chrome'] #, 'firefox']

    steps:
      - uses: actions/checkout@v1

      - uses: shivammathur/setup-php@master
        with:
          coverage: none
          php-version: '7.3'

      - name: Install sqlite3 and graphicsmagick packages
        run: sudo apt-get install sqlite3 graphicsmagick

      - name: Get build environment
        run: git clone --depth 1 https://github.com/thunder/thunder-admin-tests.git -b task/github-actions ${HOME}/build/thunder/thunder-admin-tests

      - name: Setup environment variables
        run: |
          echo "::add-path::$HOME/.composer/vendor/bin"
          echo "::add-path::$HOME/build/thunder/thunder-admin-tests/scripts"
          echo "::add-path::$HOME/build/test-dir/bin"

      - name: Get commit trigger variables
        run: source get-env-from-commit.sh

      - name: Download build
        uses: actions/download-artifact@v1
        with:
          name: build

      - name: Unzip build artifact
        run: tar xCfz ${HOME} build/build.tgz build/test-dir

      - name: Build theme
        run: build-theme.sh

#      - name: Setup visual regression testing
#        run: setup-visual.sh
#        env:
#          SHARPEYE_BROWSER: ${{ matrix.SHARPEYE_BROWSER }}

      - name: Visual regression testing
        run: |
          echo "JOB_ID: ${JOB_ID}"
          visual.sh
        env:
          JOB_ID: ${{ GITHUB_RUN_ID }}
          SHARPEYE_BROWSER: ${{ matrix.SHARPEYE_BROWSER }}

      - name: Upload images
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: images
          path: /tmp/sharpeye

      - name: Update screenshots
        run: update-screenshots.sh



