name: Visual regression tests

on:
  push:
    branches:
      - '8.x-3.x'
  pull_request:
    paths-ignore:
      - '**.md'
  schedule:
    - cron:  '0 6 * * *'

jobs:
  ### Build job
  build:
    runs-on: ubuntu-latest

    env:
      THUNDER: '8.x-4.x'
      #DRUPAL_CORE: '8.7.x'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - uses: shivammathur/setup-php@master
      with:
        coverage: none
        php-version: '7.3'

    - name: Install sqlite3 packages
      run: sudo apt-get install sqlite3

    - name: Get build environment
      run: git clone --depth 1 https://github.com/thunder/thunder-admin-tests.git -b 3.x ${HOME}/build/thunder/thunder-admin-tests

    - name: Cache composer dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-cache-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Setup environment variables
      run: |
        echo "::add-path::$HOME/.composer/vendor/bin"
        echo "::add-path::$HOME/build/thunder/thunder-admin-tests/scripts"
        echo "::add-path::$HOME/build/test-dir/bin"

    - name: Build composer project
      run: build-codebase.sh
      env:
        THUNDER: ${{ env.THUNDER }}
        DRUPAL_CORE: ${{ env.DRUPAL_CORE }}

    - name: Install application
      run: install-application.sh

    - name: Zip build
      run: cd ${HOME}; tar cfz build.tgz build/test-dir; mv build.tgz ${GITHUB_WORKSPACE}

    - name: Upload build
      uses: actions/upload-artifact@v1
      with:
        name: build
        path: build.tgz

  ### Visual regression testing job
  visual:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        SHARPEYE_BROWSER: ['chrome', 'firefox']

    steps:
    - uses: actions/checkout@v1

    - uses: shivammathur/setup-php@master
      with:
        coverage: none
        php-version: '7.3'

    - name: Install sqlite3 and graphicsmagick packages
      run: sudo apt-get install sqlite3 graphicsmagick

    - name: Get build environment
      run: git clone --depth 1 https://github.com/thunder/thunder-admin-tests.git -b 3.x ${HOME}/build/thunder/thunder-admin-tests

    - name: Cache NPM dependencies
      id: npm-cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Setup environment variables
      run: |
        echo "::add-path::$HOME/.composer/vendor/bin"
        echo "::add-path::$HOME/build/thunder/thunder-admin-tests/scripts"
        echo "::add-path::$HOME/build/test-dir/bin"

    - name: Download build
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Unzip build artifact
      run: tar xCfz ${HOME} build/build.tgz build/test-dir; rm -rf build

    - name: Build theme
      run: build-theme.sh

    - name: Visual regression testing
      run: visual.sh
      env:
        JOB_ID: ${{ github.run_id }}
        SHARPEYE_BROWSER: ${{ matrix.SHARPEYE_BROWSER }}

    - name: Upload images
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: images-${{ matrix.SHARPEYE_BROWSER }}
        path: /tmp/sharpeye

    - id: message
      name: Get commit message
      if: failure()
      run: echo "::set-output name=message::$(git log --no-merges -1 --oneline)"

    - name: Update screenshots
      if: failure() && github.event_name == 'pull_request' && contains(steps.message.outputs.message, '[UPDATE_SCREENSHOTS')
      run: update-screenshots.sh
      env:
        JOB_ID: ${{ github.run_id }}
        SHARPEYE_BROWSER: ${{ matrix.SHARPEYE_BROWSER }}
        BRANCH: ${{ github.head_ref }}
        REPOSITORY: ${{ github.repository }}
        GITHUB_TOKEN: ${{ secrets.TechAccountToken }}
